### ISSUE TITLE
Dify SHA256 error

### ISSUE THREAD

**Issue by DavideDelbianco** [langgenius/dify-plugin-daemon#252]
The dify executable installed through Brew has the following error:

Error: dify: SHA256 mismatch
Expected: 4204bfb415279cadd7462c1ac42c85c27ea08babe65bfdbe9a0bc3d7fe01de0a
  Actual: 4a0e16d030413da7c15bbc88b59bbbc9f5b0aa153b8d67e18de931dbb3a6ffd3

version of dify tool should be 0.0.9

**Comment by Yeuoly** [comment]
It should has been fixed, try `homebrew untap langgenius/dify` and reinstall again

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/39bcf275-b823-42d1-a435-35a7901f779e" />

**Comment by DavideDelbianco** [comment]
You tested it on a MAC
The Linux version still won't install

![Image](https://github.com/user-attachments/assets/7632f7f8-6978-4404-a052-4d93601e9ef6)
